### ISSUE TITLE
POVME doesn't work with smal GridSpacings and large radii: numpy.core._exceptions._ArrayMemoryError

### ISSUE THREAD

**Issue by thalesdovm** [durrantlab/POVME#1]
Does anyone know how to fix it? Or what is the problem I'm having? I'm a newbie.
I'm getting the following message when I try to use POVME with small grid spacings and large radii:
numpy.core._exceptions._ArrayMemoryError: unable to allocate 9 GiB for an array with shape (37910, 37910) and data type float64

![error](https://github.com/durrantlab/POVME/assets/140725691/144f08ab-0c7b-4a86-adae-7847df771796)

See a sample of the script below:
Parameters:
	GridSpacing: 0.4
	PointsIncludeRegions: sphere at (5.912, 2.767, 17.236), radius = 14.0
	SavePoints: True
	PDBFileName: protein-final.pdb
	DistanceCutoff: 1.09
	ConvexHullExclusion: True
	ContiguousPocketSeedRegions: sphere at (5.912, 2.767, 17.236), radius = 4.0
	ContiguousPointsCriteria: 3
	NumProcessors: 4
	UseDiskNotMemory: False
	OutputFilenamePrefix: pov04/POVME_
	SaveIndividualPocketVolumes: True
	SavePocketVolumesTrajectory: False
	OutputEqualNumPointsPerFrame: False
	SaveTabbedVolumeFile: True
	SaveVolumetricDensityMap: False
	CompressOutput: False

**Comment by jacobdurrant** [comment]
Thanks for reaching out about the issue you're experiencing with POVME. The error message you shared indicates that there is a memory allocation problem when using small grid spacings and large radii. This is likely due to the large number of points in your point field, which exceeds your computer's available memory.

To overcome this error, I would recommend increasing the grid spacing. By using a larger grid spacing, you can reduce the number of points and alleviate the memory allocation issue. 

I hope this suggestion helps fix the problem you're encountering. Best of luck with your project!

**Comment by thalesdovm** [comment]
Thank you for your reply! Is there a way to change the "UseDiskNotMemory" parameter from true to false? ChatGPT suggests it as a way to circumvent this issue:

Use Disk Space Instead of Memory (UseDiskNotMemory):
The "UseDiskNotMemory" parameter is set to False in the provided output. Changing it to True can reduce memory usage by storing intermediate results on disk. This option may lead to slower processing due to disk I/O but can be helpful when memory resources are limited.

**Comment by aalexmmaldonado** [comment]
The `UseDiskNotMemory` option only affects how the PDB file is loaded.

https://github.com/durrantlab/POVME/blob/ab929dc502f8abb81c647f3cf3c3534aa080b77a/povme/povme.py#L818-L821

[`squareform`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.squareform.html) does not allow you to store arrays on disk (for example, [`np.memmap`](https://numpy.org/doc/stable/reference/generated/numpy.memmap.html)) which is responsible for your calculation failing.

So your options are:

- run the same calculation on a computer with more memory;
- increase the grid size as mentioned above.
