### ISSUE TITLE
after install，input povme in cmd, occur No module named 'povme.cli'

### ISSUE THREAD

**Issue by gaorongchao** [durrantlab/POVME#4]
Traceback (most recent call last):
  File "/home/zhihai/software/POVME/.pixi/envs/default/bin/povme", line 5, in <module>
    from povme.cli import povme_cli
ModuleNotFoundError: No module named 'povme.cli'

**Comment by aalexmmaldonado** [comment]
Hey @gaorongchao, the command-line interface is currently being worked on and will be done today. I will also be adding documentation to help explain how to use the new interface.
